### ISSUE TITLE
Creating Access Control Function

### ISSUE THREAD

**Issue by bentsea** [stevelittlefish/flaskfilemanager#5]
Where do you define your access control function? When I attempt to access the session data inside of my app factory or current user from login manager, even when using with app.app_context() I get a working outside of request context error.

def my_access_control_function():
	"""
	:return: True if the user is allowed to access the filemanager, otherwise False
	"""
	# You can do whatever permission check you need here
	return 'logged_in' in session and session['role'] == 'admin'

**Comment by stevelittlefish** [comment]
It doesn't matter where you define your function.  If you are getting that error you are probably either calling your access control function somewhere instead of just passing it into flaskfilemanager.init or you may have accidentally unindented a line so that it's accessing the session data after the function is declared.

Here is an example from easycms (https://github.com/stevelittlefish/easycms/blob/master/easycms/__init__.py):

```
def ffm_ac_fun():
    return ac.can_access_filemanager()

flaskfilemanager.init(app, url_prefix=settings.filemanager_url_prefix,
                      access_control_function=ffm_ac_fun)
```

Make sure when you pass in your access control function you don't call it (i.e. there are no brackets after ffm_ac_fun on the last line above.

**Comment by bentsea** [comment]
I was importing the tools to detect the current user before the auth and db were initialized, so I just needed to fix my circular dependencies....  works great,and thank you so much!
